### ISSUE TITLE
Crash when using quotation marks

### ISSUE THREAD

**Issue by johnro76** [jasons-gh/the-chomsky-index#3] opened 2021-08-05 17:01 UTC
**Environment**
Linux version 5.10.32-051032-generic (kernel@gloin) (gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0, GNU ld (GNU Binutils for Ubuntu) 2.35.1)

**Steps to reproduce**
Run ./display
Do a search for a phrase and use quotation marks, e.g. search for "failed state"
program crashes with this output:
Traceback (most recent call last):
  File "display.py", line 29, in run
  File "display.py", line 385, in search_button_signal
  File "search.py", line 67, in search_results
  File "pandas/core/frame.py", line 3599, in __setitem__
  File "pandas/core/frame.py", line 3724, in _set_item_frame_value
ValueError: Columns must be same length as key
Aborted (core dumped)

**Comment by jasons-gh** [comment] 2021-08-09 20:13
Thanks for this - there were two problems. The first was that a newer version of the pandas library works differently and caused the error. I've now specified the pandas version in requirements.txt. This fixes the above issue for Linux. The second is that Windows doesn't allow double quotes in file names, which is currently required for searching articles if the entry contains a double quote, so double quotes are no longer allowed in searches. These are in the repository code and will be in the next release.

**Comment by johnro76** [comment] 2021-08-16 15:27
Hi.  I noticed something else that might be a factor.  I think it also crashes when there are no results found for a search.

**Comment by jasons-gh** [comment] 2021-08-16 20:22
Yep, that should also be caused by the newer version of pandas, so the older version in the updated requirements.txt should fix it.

**Closed as completed** 2021-08-26 13:01 UTC
